"use client";
import { useState, useEffect, useRef } from "react";
const B="#2B7FFF",BG="#07090D",BG2="#0C1017";
function useV(t=0.1){const r=useRef(null),[v,s]=useState(false);useEffect(()=>{const e=r.current;if(!e)return;const o=new IntersectionObserver(([x])=>{if(x.isIntersecting){s(true);o.disconnect()}},{threshold:t});o.observe(e);return()=>o.disconnect()},[t]);return[r,v]}
function FI({children,delay=0}){const[r,v]=useV();return(<div ref={r} style={{opacity:v?1:0,transform:v?"translateY(0)":"translateY(24px)",transition:`opacity .6s ease ${delay}s, transform .6s ease ${delay}s`}}>{children}</div>)}
function Logo(){return(<img src="/logo.png" alt="Fresh Leads Marketing" style={{height:32,width:"auto",display:"block"}}/>)}
function MobileMenu({open,onClose}){if(!open)return null;const links=[["Home","/"],["Services","/services"],["Geo-Fencing Ads","/services/geo-fencing-ads"],["Email & SMS","/services/email-sms"],["CRM Integration","/services/crm"],["AI Chatbot & Voice AI","/services/ai-chatbot"],["Google Reviews","/services/google-reviews"],["B2B Outreach","/services/b2b-outreach"],["About","/about"],["Pricing","/pricing"],["Blog","/blog"],["FAQ","/faq"],["Contact","/contact"]];return(<div className="mobile-menu-overlay" onClick={onClose}><div onClick={e=>e.stopPropagation()} style={{flex:1}}><div style={{position:"absolute",top:20,right:24}}><button onClick={onClose} style={{background:"none",border:"none",color:"#fff",fontSize:28,cursor:"pointer",padding:8}}>✕</button></div><div style={{display:"flex",flexDirection:"column",gap:4}}>{links.map(([label,href])=>{const isSub=["Geo-Fencing Ads","AI Chatbot & Voice AI","Email & SMS","CRM Integration","B2B Outreach","Google Reviews"].includes(label);return(<a key={href+label} href={href} onClick={onClose} style={{color:isSub?"rgba(255,255,255,0.4)":"#fff",textDecoration:"none",fontSize:isSub?15:20,fontWeight:isSub?500:700,padding:isSub?"6px 0 6px 20px":"10px 0",borderBottom:label==="Google Reviews"||label==="Contact"?"none":label==="Services"?"none":"1px solid rgba(255,255,255,0.05)"}}>{label}</a>)})}</div><a href="/contact" style={{display:"block",background:"#2B7FFF",color:"#fff",padding:"16px 0",borderRadius:12,fontWeight:700,fontSize:16,textDecoration:"none",textAlign:"center",marginTop:28}}>Free Marketing Audit</a></div></div>);}
function ServicesDropdown(){const [open,setOpen]=useState(false);const timer=useRef(null);const show=()=>{clearTimeout(timer.current);setOpen(true)};const hide=()=>{timer.current=setTimeout(()=>setOpen(false),150)};const items=[["Geo-Fencing Ads","/services/geo-fencing-ads"],["Email & SMS","/services/email-sms"],["CRM Integration","/services/crm"],["AI Chatbot & Voice AI","/services/ai-chatbot"],["Google Reviews","/services/google-reviews"],["B2B Outreach","/services/b2b-outreach"]];return(<div style={{position:"relative"}}onMouseEnter={show}onMouseLeave={hide}><a href="/services"style={{color:"rgba(255,255,255,0.5)",textDecoration:"none",fontSize:13,fontWeight:550,display:"flex",alignItems:"center",gap:4}}>Services<svg width="10"height="10"viewBox="0 0 10 10"fill="none"><path d="M2.5 4L5 6.5L7.5 4"stroke="currentColor"strokeWidth="1.5"strokeLinecap="round"strokeLinejoin="round"/></svg></a>{open&&(<div style={{position:"absolute",top:"100%",left:"50%",transform:"translateX(-50%)",paddingTop:10}}><div style={{background:"rgba(12,16,23,0.98)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:12,padding:"8px 0",minWidth:200,boxShadow:"0 8px 32px rgba(0,0,0,0.5)",backdropFilter:"blur(20px)"}}>{items.map(([label,href])=>(<a key={href}href={href}style={{display:"block",padding:"9px 18px",color:"rgba(255,255,255,0.6)",textDecoration:"none",fontSize:13,fontWeight:500,transition:"background .15s"}}onMouseEnter={e=>{e.target.style.background="rgba(43,127,255,0.08)";e.target.style.color="#fff"}}onMouseLeave={e=>{e.target.style.background="transparent";e.target.style.color="rgba(255,255,255,0.6)"}}>{label}</a>))}<div style={{borderTop:"1px solid rgba(255,255,255,0.06)",margin:"6px 0"}}/><a href="/services"style={{display:"block",padding:"9px 18px",color:"#2B7FFF",textDecoration:"none",fontSize:13,fontWeight:650}}>All Services →</a></div></div>)}</div>)}
function Nav(){const[mobileOpen,setMobileOpen]=useState(false);useEffect(()=>{if(mobileOpen)document.body.style.overflow="hidden";else document.body.style.overflow="";return()=>{document.body.style.overflow=""}},[mobileOpen]);return(<><nav style={{position:"fixed",top:0,left:0,right:0,zIndex:100,background:"rgba(7,9,13,0.92)",backdropFilter:"blur(20px)",borderBottom:"1px solid rgba(255,255,255,0.08)"}}><div style={{maxWidth:1200,margin:"0 auto",padding:"0 24px",display:"flex",alignItems:"center",justifyContent:"space-between",height:68}}><a href="/"><Logo/></a><div className="dn"style={{display:"flex",alignItems:"center",gap:24}}><a href="/"style={{color:"rgba(255,255,255,0.5)",textDecoration:"none",fontSize:13,fontWeight:550}}>Home</a><ServicesDropdown/>{["About","Blog","FAQ","Contact"].map(l=>(<a key={l}href={l==="About"?"/about":l==="Pricing"?"/pricing":l==="Blog"?"/blog":l==="FAQ"?"/faq":"/contact"}style={{color:"rgba(255,255,255,0.5)",textDecoration:"none",fontSize:13,fontWeight:550}}>{l}</a>))}<a href="/contact"style={{background:B,color:"#fff",padding:"9px 20px",borderRadius:9,fontWeight:650,fontSize:13,textDecoration:"none"}}>Free Marketing Audit</a></div><button className="mobile-menu-btn" onClick={()=>setMobileOpen(true)} style={{background:"none",border:"none",cursor:"pointer",padding:8,display:"none",alignItems:"center",justifyContent:"center"}}><svg width="24"height="24"viewBox="0 0 24 24"fill="none"stroke="#fff"strokeWidth="2"strokeLinecap="round"><line x1="3"y1="6"x2="21"y2="6"/><line x1="3"y1="12"x2="21"y2="12"/><line x1="3"y1="18"x2="21"y2="18"/></svg></button></div></nav><MobileMenu open={mobileOpen}onClose={()=>setMobileOpen(false)}/></>)}
function Footer(){return(<footer style={{background:BG,padding:"60px 24px 32px",borderTop:"1px solid rgba(255,255,255,0.05)"}}><div className="footer-inner" style={{maxWidth:1200,margin:"0 auto",display:"grid",gridTemplateColumns:"repeat(4, 1fr)",gap:40,marginBottom:40}}><div><Logo/><p style={{fontSize:13,color:"rgba(255,255,255,0.4)",lineHeight:1.6,marginTop:12,marginBottom:16}}>Marketing built exclusively for laundromats.</p><div style={{fontSize:13,color:"rgba(255,255,255,0.4)",marginBottom:8}}><div style={{marginBottom:6}}>📞 <a href="tel:808-736-1539" style={{color:"rgba(255,255,255,0.6)",textDecoration:"none"}}>808-736-1539</a></div><div>📧 <a href={"mailto:"+"info"+"@"+"freshleadsmarketing.com"} style={{color:"rgba(255,255,255,0.6)",textDecoration:"none"}}>{['info','@','freshleadsmarketing','.com'].join('')}</a></div></div></div><div><h4 style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:16}}>Quick Links</h4><div style={{display:"flex",flexDirection:"column",gap:8}}>{[["Home","/"],["Services","/services"],["About","/about"],["Pricing","/pricing"],["Blog","/blog"],["FAQ","/faq"],["Contact","/contact"]].map(([label,href])=>(<a key={href} href={href} style={{fontSize:13,color:"rgba(255,255,255,0.4)",textDecoration:"none",transition:"color .2s"}} onMouseEnter={e=>e.target.style.color="#fff"} onMouseLeave={e=>e.target.style.color="rgba(255,255,255,0.4)"}>{label}</a>))}</div></div><div><h4 style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:16}}>Services</h4><div style={{display:"flex",flexDirection:"column",gap:8}}>{[["Geo-Fencing Ads","/services/geo-fencing-ads"],["Email & SMS","/services/email-sms"],["CRM Integration","/services/crm"],["AI Chatbot & Voice AI","/services/ai-chatbot"],["Google Reviews","/services/google-reviews"],["B2B Outreach","/services/b2b-outreach"]].map(([label,href])=>(<a key={href} href={href} style={{fontSize:13,color:"rgba(255,255,255,0.4)",textDecoration:"none",transition:"color .2s"}} onMouseEnter={e=>e.target.style.color="#fff"} onMouseLeave={e=>e.target.style.color="rgba(255,255,255,0.4)"}>{label}</a>))}</div></div><div><h4 style={{fontSize:13,fontWeight:700,color:"#fff",marginBottom:16}}>Legal</h4><div style={{display:"flex",flexDirection:"column",gap:8}}>{[["Privacy Policy","/privacy"],["Terms of Service","/terms"]].map(([label,href])=>(<a key={href} href={href} style={{fontSize:13,color:"rgba(255,255,255,0.4)",textDecoration:"none",transition:"color .2s"}} onMouseEnter={e=>e.target.style.color="#fff"} onMouseLeave={e=>e.target.style.color="rgba(255,255,255,0.4)"}>{label}</a>))}</div></div></div><div style={{borderTop:"1px solid rgba(255,255,255,0.05)",paddingTop:24,textAlign:"center"}}><p style={{fontSize:12,color:"rgba(255,255,255,0.2)",margin:0}}>© 2026 Fresh Leads Marketing. All rights reserved.</p></div></footer>)}

export default function BlogPost() {
  return (<div style={{fontFamily:"'DM Sans', -apple-system, sans-serif",background:BG,minHeight:"100vh"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&display=swap');*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{background:#07090D;overflow-x:hidden}::selection{background:rgba(43,127,255,0.25)}@media(max-width:768px){.dn{display:none!important}.mobile-menu-btn{display:flex!important}}`}</style>
    <Nav/>
    <article style={{maxWidth:720,margin:"0 auto",padding:"120px 24px 60px"}}>
      <a href="/blog" style={{color:B,fontSize:13,fontWeight:600,textDecoration:"none",marginBottom:20,display:"inline-block"}}>← Back to blog</a>
      <div style={{display:"flex",gap:12,marginBottom:16}}>
        <span style={{background:"rgba(43,127,255,0.08)",color:B,padding:"4px 12px",borderRadius:6,fontSize:12,fontWeight:600}}>Strategy</span>
        <span style={{color:"rgba(255,255,255,0.3)",fontSize:13}}>Jan 13, 2026 · 7 min read</span>
      </div>
      <h1 style={{fontSize:"clamp(28px,4vw,42px)",fontWeight:800,color:"#fff",lineHeight:1.15,marginBottom:24}}>Building a Customer Database From Zero: A Guide for New Laundromats</h1>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>Every marketing strategy starts with customer data</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>You can't send win-back emails without knowing who lapsed. You can't segment VIPs without tracking visit frequency. You can't measure ROI without connecting revenue to marketing channels. Everything starts with a customer database.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>If you're opening a new laundromat or taking over an existing one that never tracked customers, here's exactly how to build your <a href='/services/crm' style={{color:'#2B7FFF'}}>CRM database</a> from scratch.</p>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>Step 1: Connect your POS system</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Your POS is the backbone of your customer database. Every transaction captures data. At minimum a payment method, and ideally a name, phone number, or email. Cents, LaundroWorks, and CCI all have the ability to capture and export customer data.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>If you're choosing a POS for a new laundromat, prioritize one that captures customer contact info at the point of sale. This single decision will determine how fast your database grows.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>We integrate directly with these systems so data flows into your CRM automatically. No manual entry, no CSV exports.</p>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>Step 2: Add QR codes everywhere</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Physical QR codes are the fastest way to capture contacts from walk-in customers. Place them at the counter, on each machine, on the bulletin board, and at the entrance.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Each QR code should link to a simple form offering something in return: '20% off your next wash & fold' or 'Join our VIP list for exclusive deals.' The exchange of value is important. People won't give their phone number for nothing.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>A well-placed QR code system can add 5-15 new contacts per day without any staff involvement.</p>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>Step 3: Use your AI chatbot as a lead capture tool</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Every conversation your <a href='/services/ai-chatbot' style={{color:'#2B7FFF'}}>AI chatbot</a> has is an opportunity to capture a contact. When someone asks about hours, the bot answers and then says 'Want me to text you our weekly specials? Just drop your number below.'</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>This feels natural and helpful. Not salesy. The contact goes directly into your CRM, tagged with the source so you can track which channels generate the most leads.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Our chatbots capture an average of 30-50 new contacts per month from website visitors alone.</p>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>Step 4: Launch review request flows</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Your <a href='/services/google-reviews' style={{color:'#2B7FFF'}}>Google review system</a> does double duty: it generates reviews AND captures customer data. When you send a review request via SMS, that phone number goes into your database.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Even if someone doesn't leave a review, you now have their contact info for future marketing. It's a list-building strategy disguised as a reputation strategy.</p>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>Step 5: Run a launch promotion</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>For new laundromats, nothing builds a database faster than a compelling launch offer promoted through geo-fencing ads. 'Grand Opening: First wash free!' or 'Opening special: 50% off wash & fold all week.'</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Run these ads to everyone within a 3-5 mile radius. Every person who redeems the offer becomes a contact in your database. From there, your automated sequences take over. Welcome emails, follow-up offers, review requests.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>We've seen new laundromats go from zero to 500+ contacts within their first 60 days using this approach.</p>
        <h2 style={{fontSize:22,fontWeight:800,color:"#fff",marginTop:40,marginBottom:14}}>The compound effect of a growing database</h2>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>A customer database is a compounding asset. At 200 contacts, a win-back campaign might generate $1,000. At 2,000 contacts, the same campaign generates $10,000. Your database grows every day while the cost of marketing to it stays flat.</p>
        <p style={{fontSize:16,color:"rgba(255,255,255,0.55)",lineHeight:1.75,marginBottom:18}}>Start building from day one. Don't wait until you 'need' marketing. By the time you realize you need it, you'll wish you'd been collecting data for months.</p>

      <div style={{background:"rgba(43,127,255,0.04)",border:"1px solid rgba(43,127,255,0.15)",borderRadius:16,padding:"32px 28px",marginTop:48,textAlign:"center"}}>
        <h3 style={{fontSize:20,fontWeight:800,color:"#fff",marginBottom:8}}>Starting from zero?</h3>
        <p style={{fontSize:15,color:"rgba(255,255,255,0.5)",marginBottom:16,lineHeight:1.6}}>Book a free call and we'll help you set up a CRM and customer capture system from day one.</p>
        <a href="/contact" style={{display:"inline-block",background:B,color:"#fff",padding:"14px 28px",borderRadius:10,fontWeight:700,fontSize:15,textDecoration:"none"}}>Schedule Your Free Audit →</a>
      </div>
    </article>
    <Footer/>
  </div>);
}
